[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.simple"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
